@Scribbly.Cubby.Hosted_HostAddress = http://localhost:5033

GET {{Scribbly.Cubby.Hosted_HostAddress}}/
Accept: application/json

###

GET {{Scribbly.Cubby.Hosted_HostAddress}}/
Accept: application/json

###
