@Scribbly.Cubby.Cookbook.ApiService_HostAddress = https://localhost:7514

POST {{host}}/entry/my_key
Content-Type: application/json

{
    "key": "my_key",
    "value": "my value"
}

###

GET {{host}}/entry/my_key2

###
