@Scribbly.Cubby.Cookbook.ApiService_HostAddress = https://localhost:7514

POST {{host}}/entry/my_key
Content-Type: application/json

{
    "key": "my_key",
    "value": "my value"
}

###

GET {{host}}/entry/my_key

###

POST {{host}}/cubby/client/my_key
Content-Type: application/json

{
    "key": "my_key",
    "value": "my value"
}

###

GET {{host}}/cubby/client/my_key

###

POST {{host}}/cubby/http/my_key
Content-Type: application/json

{
    "key": "my_key",
    "value": "my value"
}

### With Compression

POST {{host}}/cubby/http/my_key?compress=true
Content-Type: application/json

{
    "key": "my_key",
    "value": "my value"
}

###

GET {{host}}/cubby/http/my_key

###

POST {{host}}/cubby/grpc/my_key
Content-Type: application/json

{
    "key": "my_key",
    "value": "my value"
}

###

GET {{host}}/cubby/grpc/my_key

###
