@Scribbly.Cubby.Host_HostAddress = http://localhost:5018


###

GET {{debug}}/cubby/my_key3
Accept: application/json

### PUT 

PUT {{debug}}/cubby?key=sfghsdfhghgfsdhs
Content-Type: application/json

{
  "key": "my_key",
  "value": "my value"
}

### PUT with Expiration

PUT {{debug}}/cubby?key=my_key3
Content-Type: application/json
x-cubby-expiry: 00:00:10

{
  "key": "my_key",
  "value": "my value"
}


### PUT with Compression (we would need to compress the value here since it's assumed the client does the compression before crossing the wire)

PUT {{debug}}/cubby/my_key3
Content-Type: application/json
x-cubby-flags: Compressed

{
  "key": "my_key",
  "value": "my value"
}

