@Scribbly.Cubby.Host_HostAddress = http://localhost:5018


###

GET {{container}}/cubby/my_key
Accept: application/json

###

PUT {{container}}/cubby/my_key
Content-Type: application/json

{
  "key": "my_key",
  "value": "my value"
}
